reduce the amount of spelling issues / WORDLIST
insightsengineering/rtables pull request #685
Opened 2023-07-12 15:50 UTC by m7pr

A follow-up after https://github.com/insightsengineering/coredev-tasks/issues/235

I am basically trying to catch all spelling issues, and try to put \code{} around parameter names, function names, package names, object names and data structure names.

**Still a work in progress!** Current result of `spelling::spell_check_package()`

```{R}
  WORD                  FOUND IN
ard                   ard_specs.Rd:10
ARD                   ard_specs.Rd:5,13
                      as_ard.Rd:5,13,15,18,21
Arg                   compat_args.Rd:5,34
                      constr_args.Rd:5,124
                      lyt_args.Rd:5,208
                      sf_args.Rd:5,23
args                  analyze.Rd:137
                      make_afun.Rd:42
                      advanced_usage.Rmd:218
bjy                   sorting_pruning.Rmd:237
cbind                 cbind_rtables.Rd:5,18
CMD                   int_methods.Rd:1209
colcount              basic_table.Rd:52
combinatorial         split_functions.Rmd:147
comparead             sorting_pruning.Rmd:411
cpp                   paginate.Rd:88
                      tt_to_flextable.Rd:29
currentl              sorting_pruning.Rmd:232
decrementing          paginate.Rd:172
decriptor             sort_at_path.Rd:69
dimensioned           head_tail.Rd:41
ElementaryTable       df_to_tt.Rd:5,17
ie                    avarspl.Rd:116
                      cutsplits.Rd:87
                      insert_rrow.Rd:14
                      int_methods.Rd:1115
                      lyt_args.Rd:133
                      ManualSplit.Rd:22
                      MultiVarSplit.Rd:62
                      rcell.Rd:58
                      split_cols_by.Rd:45
                      split_funcs.Rd:59
                      split_rows_by.Rd:52
                      split_rows_by_multivar.Rd:49
                      tsv_io.Rd:40
                      update_ref_indexing.Rd:18
                      varcuts.Rd:138
                      VarLevelSplit.Rd:85
incr                  indent_string.Rd:19
labelrow              label_at_path.Rd:30
LabelRow              trim_prune_funs.Rd:52
LayoutColTree         cinfo.Rd:22
na                    make_afun.Rd:38
                      NEWS.md:76
rbound                add_combo_facet.Rd:32
                      int_methods.Rd:1189
rcell                 format_rcell.Rd:5
reindexed             head_tail.Rd:62
repped                analyze.Rd:85
                      analyze_colvars.Rd:21
                      names.Rd:29
reusability           clinical_trials.Rmd:401
RowsVerticalSection   counts_wpcts.Rd:15
rrowl                 rrowl.Rd:5,29
rrows                 insert_rrow.Rd:5
rtable                compare_rtables.Rd:16,18
                      is_rtable.Rd:5,16
                      make_col_row_df.Rd:13
                      matrix_form-VTableTree-method.Rd:5,46
                      row_paths_summary.Rd:13
                      trim_zero_rows.Rd:13
spl                   analyze.Rd:145
                      spl_context.Rd:5,7,9
                      spl_context_to_disp_path.Rd:5,17
TableTree             paginate.Rd:6
                      rbind.Rd:8,33
                      top_left.Rd:40
```

2023-07-12 17:16 UTC, shajoezhu commented
hi @m7pr , many thanks for this, can I suggest we do the sweep right before https://github.com/insightsengineering/rtables/issues/678? there are a few PRs are about to be merged in

2023-07-12 18:15 UTC, m7pr commented
Hey @shajoezhu - I am ready with my part. I suggest we merge now, so everything that is required by #678 will already have spell-check fixed and you will only need to figure out the new spelling issues that will be triggered by GitHub Actions spelling check. I reckon it will be easier to solve future spelling issues one-by-one on a single PR than once again once multiple PRs are merged.

2023-07-13 07:35 UTC, Melkiades commented
Thanks, Marcin to work on this. I think we need to put it on hold merging it after  https://github.com/insightsengineering/rtables/pull/665. What you think @shajoezhu @gmbecker

2023-07-13 08:01 UTC, m7pr commented on vignettes/introduction.Rmd
> +v
```suggestion

```

2023-07-13 08:02 UTC, m7pr commented on tests/testthat/test-lyt-tabulation.R
> +                 "Error.*custom split function: oopsi.e. daisy.*VarLevelSplit \\(RACE\\).*path: ARM\\[A: Drug X\\]")
```suggestion
                 "Error.*custom split function: oopsie daisy.*VarLevelSplit \\(RACE\\).*path: ARM\\[A: Drug X\\]")
```

2023-07-13 08:02 UTC, m7pr commented on tests/testthat/test-lyt-tabulation.R
> +        stop("oopsi.e. daisy")
```suggestion
        stop("oopsie daisy")
```

2023-07-13 09:10 UTC, Melkiades commented
> IMHO the sooner you merge, the sooner you start paying attention to spelling anywhere

Trust me, we did know very well about the problem which predates the current SME team.

Anyway, if you insist we can merge it in already, but I have the feeling that this is going to break all PRs currently open and it is not a great timing for this. 

In general, we need to collaborate on this, and at least warn us about it. Just let us know before starting working on these kinds of issues as it may not be the best timing for those. Also, this work is not on Kendis, and it is clearly something that has dependencies on our team.

2023-07-13 09:26 UTC, Melkiades commented
> > IMHO the sooner you merge, the sooner you start paying attention to spelling anywhere
> 
> Trust me, we did know very well about the problem which predates the current SME team.
> 
> Anyway, if you insist we can merge it in already, but I have the feeling that this is going to break all PRs currently open and it is not a great timing for this.

But this is my council: flag this on @gogonzo to liaison with @shajoezhu on the best way forward before any merge is being considered. In the interim, hold fire on this one.

2023-07-13 09:52 UTC, pawelru commented
> In general, we need to collaborate, and please at least warn us about it beforehand

Apologies guys. The whole blame is on me. Bad planning. I chatted with Marcin and I ask him to complete that for rtables repo. Anyway, @shajoezhu please make a call what to do with this PR. Even if it will wait - I don't expect a lot of complex git conflicts to be resolved.

2023-07-13 09:53 UTC, shajoezhu commented
hey guys, thanks for working on this. I am blocking the merge for now

2023-07-13 10:09 UTC, m7pr commented
Apologies, I was not aware that there is release going on. Take your time to merge it. Flag me also when you think it can be merged and I'll fix conflicts and update files after you made changes to your PRs.

2023-07-13 13:20 UTC, shajoezhu requested changes
hi @m7pr , can you add a NEWS entry please. Thanks!

2023-07-14 07:24 UTC, m7pr commented
Yes @shajoezhu - I did fix conflicts and updated NEWS with a relevant note about the spelling revision

2023-07-28 13:39 UTC, shajoezhu approved these changes
lgtm! many thanks @m7pr

2023-07-28 13:41 UTC, merged