872 as html fix@main
insightsengineering/rtables pull request #873
Opened 2024-05-29 00:09 UTC by ayogasekaram

closes #872

2024-05-30 21:49 UTC, edelarua approved these changes
Lgtm!

2024-06-07 08:45 UTC, Melkiades commented on R/as_html.R
> +
I think you need to remove these

2024-06-07 08:46 UTC, Melkiades commented on R/as_html.R
> +  for (i in 1:nr) {
```suggestion
  for (i in seq_len(nr)) {
```

2024-06-07 08:47 UTC, Melkiades commented on R/as_html.R
> +      should_display_col <- apply(mf_display(mat)[rows, , drop = FALSE], 2, any)
Thanks Abi!! this was really needed (also everywhere else in principles)

2024-06-07 19:52 UTC, edelarua requested changes
Hi @ayogasekaram,

The row labels style section you removed isn't currently used in teal apps but is still useful (and could be implemented there in the future).

For example, when the following code is run, see the difference in html output with/without this section included:

```r
tbl <- basic_table() %>%
  split_rows_by("BMRKR2") %>%
  analyze("AGE") %>%
  build_table(ex_adsl)

Viewer(tbl, bold = c("header", "row_names"))
```

Produces without this section:
![Screenshot 2024-06-07 154729](https://github.com/insightsengineering/rtables/assets/59304861/e35bd38a-5737-4970-9609-c813deef7056)

Produces with this section:
![Screenshot 2024-06-07 154744](https://github.com/insightsengineering/rtables/assets/59304861/5509bbdb-6dc0-45a5-b504-00b64125c9d8)

I would add the removed code back in (and maybe another example like the one I gave above?) and then I think you're good to go. That should also fix the failing test :)

Thanks!!

2024-06-07 21:29 UTC, edelarua commented
Sorry, I forgot to also mention that the indentation code (each indent is tripled) was requested at one point to improve visibility within teal modules.

For example,

Without indentation:
  
  ![Screenshot 2024-06-07 172520](https://github.com/insightsengineering/rtables/assets/59304861/0a19c81a-cbbf-4029-ac46-1603b6ea6e72)

With indentation:
  
  ![Screenshot 2024-06-07 172359](https://github.com/insightsengineering/rtables/assets/59304861/3a2d2489-2fa7-46c7-a315-b2ff5ef674f4)

2024-06-11 02:36 UTC, shajoezhu commented
hi @ayogasekaram , could you raise PRs downstream, and see how much downstream breaking changes there will be. thanks!

- [ ] tern
- [ ] tern.rbmi
- [ ] tern.gee
- [ ] tern.mmrm
- [ ] teal.modules.clinical
- [ ] scda.test

Thanks a lot!

2024-06-11 12:57 UTC, ayogasekaram commented
> hi @ayogasekaram , could you raise PRs downstream, and see how much downstream breaking changes there will be. thanks!
> 
> * [ ]  tern
> * [ ]  tern.rbmi
> * [ ]  tern.gee
> * [ ]  tern.mmrm
> * [ ]  teal.modules.clinical
> * [ ]  scda.test
> 
> Thanks a lot!

Hey @shajoezhu! Thanks for taking a look. There shouldn't be downstream changes in any of those packages as they don't call the `as_html` function. The function also should work exactly as before - it just accommodates the newline character if present so there aren't any tables that were modified. I ran the checks for each of those packages locally with this rtables change and they've all passed but I can raise the PRs just in case!

2024-06-11 13:48 UTC, shajoezhu commented
@ayogasekaram I see. I saw an indentation change, and thought that might be breaking changes. can you give it a try for scda.test, if everything is ok, we can quickly move on, and include this in the coming release. thanks!

2024-06-11 14:08 UTC, ayogasekaram commented
@shajoezhu No errors in scda.test :)

2024-06-11 14:36 UTC, edelarua reviewed
Hi Abi! Just a few small comments.

2024-06-11 14:36 UTC, edelarua commented on NEWS.md
> + * update `as_html` to accommodate `\n` characters.
Past tense
```suggestion
 * Updated `as_html` to accommodate `\n` characters.
```

2024-06-11 14:36 UTC, edelarua commented on R/as_html.R
> +  cells <- matrix(rep(list(list()), (nr) * (nc)), ncol = nc)
Don't really need the extra brackets
```suggestion
  cells <- matrix(rep(list(list()), nr * nc), ncol = nc)
```

2024-06-11 14:36 UTC, edelarua commented on R/as_html.R
> -
Why was this section removed? I don't think it's related to the changes for `\n` since it only controls bolding for label rows

2024-06-11 20:16 UTC, edelarua approved these changes
Lgtm - thanks Abi!!

2024-06-12 15:35 UTC, Melkiades approved these changes
Lgtm!! Thanks Abi :) wonderful work

2024-06-12 16:22 UTC, merged