Adding stat_names and support for row/col splits and `ContentRow`
insightsengineering/rtables pull request #958
Opened 2024-11-21 12:20 UTC by Melkiades

…row_groups

2024-11-27 16:30 UTC, Melkiades commented
@edelarua @ayogasekaram @BFalquet this is ready for review ;) Thanks!!

2024-11-28 00:04 UTC, edelarua requested changes
Hi @Melkiades,

Thanks for working on this - it looks great!! I have a few questions/observations, but I'm not sure how closely we're trying to match the output from {cards} so some of it may not be relevant.

I also made a few updates to the ARD vignette but it's just spelling/grammar stuff (no code changes). Let me know if you have any questions about that.

2024-11-28 10:47 UTC, Melkiades commented on tests/testthat/test-result_data_frame.R
> +      spl_value_2 = "S2",
I wanted to keep the information about row or col splits, I guess I can add a column about that and make it uniform

2024-11-28 10:55 UTC, Melkiades commented on R/tt_as_df.R
> +.get_stat_names_from_table <- function(tt, add.labrows = FALSE) {
Done. The rest of the package does not follow this but I think it is local enough to respect this ;)

2024-11-28 11:15 UTC, Melkiades commented on tests/testthat/test-result_data_frame.R
> +      spl_value_2 = "S2",
mmh no because it is flatten out. I think it is fine to have everything group*

2024-11-28 11:32 UTC, Melkiades commented on tests/testthat/test-result_data_frame.R
> +      group2_level = "S2",
fixed at source

2024-11-28 12:09 UTC, Melkiades commented on tests/testthat/test-result_data_frame.R
> +      spl_value_1 = "S1",
it makes sense, it is fixed now!

2024-11-28 22:22 UTC, edelarua approved these changes
I think this looks good now! Thanks for the updates @Melkiades

2024-11-29 10:21 UTC, merged